### ISSUE TITLE
Recently Updated Deals incorrect param 'limit' should be 'count' I believe

### ISSUE THREAD

**Issue by TimWhitbeck** [hubspot-net/HubSpot.NET#34]
When getting recently updated deals the Hubspot API is looking for a parameter named 'count' from looking at the source it's attempting to set a parameter 'limit' - outcome is that no matter what 'limit' is passed in it's returning the default of 20 deals.

**Comment by Psypher9** [comment]
Thank you for pointing this out! We are in the process of making some major updates, so we will be sure to clean that up.

**Comment by TimWhitbeck** [comment]
Just a note, this seems to be causing a larger issue at least from the hubspot sandbox environment. I believe the change happened on Hubspots end. Again I haven't had the opportunity to test this against our production hubspot so in dev if i make two calls to getrecentlyupdateddeals. I get the following message on the second call "Cannot fetch more than 10000 total records for this endpoint". Seems very odd since our sandbox doesn't even have 10K records in it but I believe if we can make this use the count parameter we will be able to get past it. Any ideas on a release date?

**Comment by Psypher9** [comment]
Wow. Thanks for the update on this. I don't have a set time for when I can work on a fix for this yet. We can definitely entertain a PR on this though.

**Comment by Psypher9** [comment]
Thanks again for pointing this out @TimWhitbeck!
