### ISSUE TITLE
Issue with RestSharp version

### ISSUE THREAD

**Issue by asmith3006** [hubspot-net/HubSpot.NET#46]
I have restsharp version 106.6.9. When I try to run a HubSpot call I get the following error:

> Could not load file or assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Code example:
``` c#
 var api = new HubSpot.NET.Core.HubSpotApi("key-goes-here");
        var contact = api.Contact.Create(new HubSpot.NET.Api.Contact.Dto.ContactHubSpotModel()
        {
            Email = "john@squaredup.com",
            FirstName = "John",
            LastName = "Smith",
            Phone = "00000 000000",
            Company = "Squared Up Ltd."
        });
```

Can this package be made to run with the latest RestSharp? I can't downgrade as I won't be able to run other NuGet packages I have installed.

Thanks.

**Comment by Psypher9** [comment]
Thanks for bringing this up @asmith3006, it probably is about time to update the package. Would you like to open a PR for this issue and handle updating the package?

**Comment by clarkd** [comment]
Should be reasonably straightforward - some of the ExecuteAsync methods have renamed to ExecuteTaskAsync though.

**Comment by asmith3006** [comment]
> Would you like to open a PR for this issue and handle updating the package?

I would love to say I'm a good enough developer to do that, but I'm not - sadly.

**Comment by Psypher9** [comment]
Okay, no problem! I just wanted to leave it open to you if you would like to. We can take it!

**Comment by Psypher9** [comment]
I've updated the RestSharp version on the 81709b1 commit fot the `v1-preview` branch. This should be available soon.

**Comment by Psypher9** [comment]
@asmith3006 we won't be able to use the latest version of RestSharp in production right now, because the latest version isn't compatible with .NET Framework 4.5.1, we would need to update the framework version, which is part of the updates coming in the `v1-preview` branch.
