### ISSUE TITLE
Add support for dotnet core

### ISSUE THREAD

**Issue by bidiu** [hubspot-net/HubSpot.NET#53]
New to C# and .Net platform. Is it easy to target this library to dotnet core as well?

**Comment by Psypher9** [comment]
Hello! Our master branch does not currently support .NET Core, however using our v1-preview branch we are targeting the .NET Standard which will work with your .NET Core project.

**Comment by bidiu** [comment]
Thanks for the quick response. Should I get the v1 preview by cloning this repo and referencing it locally? 

And this is not related to the original issue topic, but does this library support the CRM Associations API? To my knowledge, the original APIs for adding contacts/deals to companies are deprecated (https://developers.hubspot.com/docs/methods/companies/add_contact_to_company).

**Comment by bidiu** [comment]
Closing this issue since the feature is in v1-preview branch.
