### ISSUE TITLE
dotnet core support

### ISSUE THREAD

**Issue by EvgenyKhaliper** [hubspot-net/HubSpot.NET#56]
Hi, 
any plans on making this package dotnet core friendly ?

warning NU1701: Package 'SquaredUp.HubSpot.NET 0.6.17' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

**Comment by Psypher9** [comment]
Yes! Actually, our v1-preview branch is currently in a PR to master. That branch is on the .NET Standard. We will update our package feeds once everything looks good to go.

**Comment by cfluke-twilio** [comment]
@Psypher9 Hey, I saw this was merged into master. Do you know when it will get published into Nuget? 

Thanks for the hard work.

**Comment by Psypher9** [comment]
@cfluke-twilio, thanks for checking in! 

It'll probably be a few weeks honestly. We've got quite a bit of testing to make sure things are still working. We would really appreciate the help if you would like to help us test what we have so far.

The working changes for the 1.0 release are pretty huge. I would be more than happy to entertain any issues you find.

**Comment by EvgenyKhaliper** [comment]
Thanks @Psypher9 !!! Will test the basics next week.
