### ISSUE TITLE
Master branch doesn't build

### ISSUE THREAD

**Issue by jokumusic** [hubspot-net/HubSpot.NET#61]
**Describe the bug**
The best overload for 'Execute' does not have a parameter named 'convertToPropertiesSchema'	HubSpot.NET (netstandard2.0)	HubSpot.NET\HubSpot.NET\Api\EmailEvents\HubSpotEmailEventsApi.cs	34

'IHubSpotClient' does not contain a definition for 'ExecuteList' and no accessible extension method 'ExecuteList' accepting a first argument of type 'IHubSpotClient' could be found (are you missing a using directive or an assembly reference?)	HubSpot.NET (netstandard2.0)	HubSpot.NET\HubSpot.NET\Api\EmailEvents\HubSpotEmailEventsApi.cs	59

**Repro Steps**
clone the master branch and then build the solution

**Expected behavior**
the solution should build without errors

*Anything else?**
I'm trying to use a version that supports OAuth, but the version in the NuGet repo doesn't.

**Comment by Psypher9** [comment]
@jokumusic thank you for bringing this up! We are currently underway with creating automated builds to ensure that we can have our code validated! I will keep you posted.

**Comment by Psypher9** [comment]
Thank you again for your issue @jokumusic, the master branch will now build and we have automated builds validating every commit and PR. Here's our build badge, which you can now see on the repo's readme.
[![Build Status](https://dev.azure.com/hubspot-net/HubSpot.NET/_apis/build/status/hubspot-net.HubSpot.NET?branchName=master)](https://dev.azure.com/hubspot-net/HubSpot.NET/_build/latest?definitionId=1&branchName=master)
