### ISSUE TITLE
ContactHubSpotModel.Email  always null

### ISSUE THREAD

**Issue by franknesse** [hubspot-net/HubSpot.NET#63]
**Describe the bug**
In all cases, the ContactHubSpotModel.Email property is null, although I am certain that each contact has a valid e-mail address. LastName and FirstName give normal response

**Repro Steps**

```
foreach (ContactHubSpotModel contact in result.Contacts)
{
		Console.WriteLine($"{contact.FirstName} {contact.LastName} {contact.Email}");
}
Console.ReadLine();
```

**Expected behavior**
Return the e-mail address as registered in HubSpot

**Screenshots**

*Anything else?**
I am new to HubSpot (integration)

**Comment by Psypher9** [comment]
Hi @franknesse, thanks for your issue. Could you please tell me which version of the package you are using and perhaps post a little more of the code you are using around this for each loop?

**Comment by franknesse** [comment]
Hello @Psypher9 , thanks for your quick reply. I am using version 0.6.17 (just installed it from NuGet). 
The code is nothng more than:

```
var api = new HubSpotApi("<my api key>");			
var result = api.Contact.List<HubSpot.NET.Api.Contact.Dto.ContactHubSpotModel>();			
foreach (ContactHubSpotModel contact in result.Contacts)
{
	Console.WriteLine($"{contact.FirstName} {contact.LastName} {contact.Email}");
}
```
And the output is: 
![image](https://user-images.githubusercontent.com/2273369/69727137-32f99880-1122-11ea-92bb-1bf78597618d.png)

And this is my hubspot application:
![image](https://user-images.githubusercontent.com/2273369/69727207-57557500-1122-11ea-8a62-81469e11d219.png)

**Comment by franknesse** [comment]
I managed to get the e-mail address now, by providing a ListRequestOptins object as follows:

```
var api = new HubSpotApi("<my api key>");
ListRequestOptions options = new ListRequestOptions()
{
	PropertiesToInclude = new List<string> { "firstname", "lastname", "email" }
};
var result = api.Contact.List<HubSpot.NET.Api.Contact.Dto.ContactHubSpotModel>(options);
foreach (ContactHubSpotModel contact in result.Contacts)
{
	Console.WriteLine($"{contact.FirstName} {contact.LastName} {contact.Email}");				
}

```
But for me it is not clear yet why last and first name are provided by default where as I need to explicitly request for the email using the ListRequestOptions  object. Can anybody explain this behavior to me?

**Comment by Psypher9** [comment]
@franknesse, this is actually due to HubSpot's API specifications [found here](https://developers.hubspot.com/docs/methods/contacts/get_contacts) under the Optional Parameter section and Property. Their API only includes a few properties (i.e. first and last name) by default when getting all contacts by this method.

**Comment by franknesse** [comment]
ok, clear. Thanks for the feedback. I will close this one.
