### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by chrismoutray** [hubspot-net/HubSpot.NET#68]
Hello, 
I'm currently starting out on integrating with HubSpot and decided to use this project, but straight away have found the nuget doesn't contain implementation for OAuth2. (Last updated Aug 2018). I can see the README shows an example using a OAuth connection. So its unclear if this project is still active. If it is, is it recommended to clone the repo directly and is it in a good state to use in a production environment?
Thanks

**Comment by Psypher9** [comment]
Hi @chrismoutray,

You are correct, the NuGet package currently does not support OAuth2. We have not released the OAuth features as of yet. Yes, if you need updated features, the recommended approach is to build from source and integrate it into your solution. 

Although there are some users using this repo in a production environment, it's really up to you to decide that through testing of the features that you need. 

We are currently in a preview of the full 1.0, so we cannot guarantee full compatibility with what you are trying to accomplish. If you find some specific issues, please open a new issue and we will try to tackle that there.

We are working with what we have to try and release a 1.0 package soon.

**Comment by Psypher9** [comment]
Thank you for reaching out @chrismoutray!

**Comment by chrismoutray** [comment]
@Psypher9 Thank you for the quick response and really appreciate the effort put into this project.
