### ISSUE TITLE
No Associations on Deals

### ISSUE THREAD

**Issue by LeeStevens318** [hubspot-net/HubSpot.NET#84]
**Describe the bug**
When pulling a list of Deals and settings the "includeAssociations" as true it's not populating the associations.

![DealApiNoAssociations](https://user-images.githubusercontent.com/28816427/87650615-42068700-c795-11ea-8cdc-d4f42a047ab0.png)

When querying the API directly the information is retrieved:

![DealApiNoAssociationsDirect](https://user-images.githubusercontent.com/28816427/87651019-dec92480-c795-11ea-8085-3977f26752e1.png)

URL:

https://api.hubapi.com/deals/v1/deal/paged?hapikey=KEY_HERE&offset=100&includeAssociations=true&limit=2&properties=job_no

**Repro Steps**
```
var deals = new List<Deal>();

try
{
	var moreResults = true;
	long offset = 0;

	while (moreResults)
	{
		var allDeals = api.Deal.List<Deal>(true,
			new ListRequestOptions
			{
				PropertiesToInclude = new List<string>
				{
					"dealname",
					"amount",
					"job_no",
					"dealtype",
					"dealstage",
					"createdate",
					"pipeline",
					"hubspot_owner_id"
				},
				Limit = 100,
				Offset = offset
			});

		deals.AddRange(allDeals.Deals);

		moreResults = allDeals.MoreResultsAvailable;
		if (moreResults)
			offset = allDeals.ContinuationOffset;
	}
}
catch (Exception e)
{
	Console.WriteLine(e);
	throw;
}
```
AND Deal Class
```
public class Deal : DealHubSpotModel
{
	/// <summary>
	/// 
	/// </summary>
	[DataMember(Name = "job_no")]
	public int JobNumber { get; set; }

	/// <summary>
	/// 
	/// </summary>
	[DataMember(Name = "createdate")]
	public long CreateDate { get; set; }
}
```

**Expected behavior**
Associations shouldn't be null

**Comment by aronsimpletix** [comment]
I'm running into an issue where I can create: Contacts, companies, deals.
**But I cannot create DealHubSpotAssociation**

**Comment by LeeStevens318** [comment]
@aronsimpletix you should be able to map associations during creation:
```
// Removed invalid code - see response below.
```

**Comment by aronsimpletix** [comment]
Hi Lee

*Associations* was not in the properties. Did you add it to your code?

**Comment by LeeStevens318** [comment]
Hi @aronsimpletix, yeah sorry i was just editing my response. I realised this was on the old package i used i switched to: https://github.com/skarpdev/dotnetcore-hubspot-client

**Comment by aronsimpletix** [comment]
That’s weird, the old package is better than the new one?
